#+TITLE: jmax - awesome editing in emacs
#+AUTHOR: John Kitchin

* Introduction
jmax is a customization of emacs that facilitates writing technical documents. I found it takes extensive customization to get emacs to do what you want, and this is my collection of customizations.

Check out the org-mode manual info:org.

** Markup shortcuts

jmax defines some shortcuts for org-mode markup. You can select text and type the shortcut to wrap the region in the markup, or type the short cut to wrap the character at point or create the markup with the cursor inside it to keep typing.

| markup            | keyshortcut | emacs-command                   |
|-------------------+-------------+---------------------------------|
| *Bold*            | s-b         | `bold-region-or-point'          |
| /italics/         | s-i         | `italics-region-or-point'       |
| =verbatim=        | s-v         | `verbatim-region-or-point'      |
| ~code~            | s-c         | `code-region-or-point'          |
| _underline_       | s-u         | `underline-region-or-point'     |
| +strike+          | s-+         | `strikethrough-region-or-point' |
| _{subscript}      | s--         | `subscript-region-or-point'     |
| ^{superscript}    | s-=         | `superscript-region-or-point'   |
| \(equation\)      | s-4         | `latex-math-region-or-point'    |
| $inline eqn$      | C-u s-4     |                                 |
| @@latex:snippet@@ | C-u C-u 4   |                                 |
| °                 | s-y         | `helm-insert-org-entity'        |
| \deg              | s-y f2      |                                 |
| \textdegree{}     | s-y f3      |                                 |
| &deg;             | s-y f4      |                                 |

Use  `helm-insert-org-entity' (s-y) for all accented characters

Here are some common ones, but there are alot of them!

| angstrom | ("AA" "\\AA{}" nil "&Aring;" "A" "Å" "Å")     |
|          | ("oslash" "\\o{}" nil "&oslash;" "o" "ø" "ø") |
|          | ("uuml" "\\\"{u}" nil "&uuml;" "ue" "ü" "ü")  |

** src-block expansion in org-mode

The following examples show the shortcuts defined in jmax for expansion. Put your cursor after the shortcut and press tab to expand them.

<p
#+BEGIN_SRC python

#+END_SRC

<por
#+BEGIN_SRC python :results output raw

#+END_SRC

<pv
#+BEGIN_SRC python :results value

#+END_SRC

<el
#+BEGIN_SRC emacs-lisp

#+END_SRC

<sh
#+BEGIN_SRC sh

#+END_SRC

<lh
#+latex_header:

<lc
#+latex_class:

<lco
#+latex_class_options:

<ao
#+attr_org:

<al
#+attr_latex:

<ca
#+caption:

<tn
#+tblname:

<n
#+name:

Here are some convenient table expansions.

<t
|  |

<tt
|  |   |

<ttt
|  |   |   |

<tttt
|  |   |   |   |

<ttttt
|  |   |   |   |   |

<tttttt
|  |   |   |   |   |   |

** LaTeX export classes in jmax
The default article class is not usually what you want your PDF documents to look like.

- cmu-article :: an article with 1inch margins and default packages
- article-no-defaults :: bare article class with no default packages

** Getting help in Emacs
jmax does a few things to help you get help besides this manual.

1. `emacs-keybinding-command-tooltip-mode'
   This minor mode recognizes command/variable syntax, fontifies it, puts a tooltip on it, and makes it clickable! The tooltip is the Emacs documentation. Clicking on it opens the Help buffer. Pressing the super key and clicking should open the code for the function.
   It recognizes variables too: `org-export-babel-evaluate'.

   The key-binding syntax is also recognized \\[bold-region-or-point] and hovering on it will show you the keybinding if there is one.

2. The `ore' command will tell you about the org-element your cursor is on. It will give you some hints about what you can do (i.e. what commands/actions you can do) at that point.

3. You may find the `jeldoc' command helpful to learn about libraries. It generates an org-file of all the requirements, variables and functions in a library. Try this link: [[elisp:(jeldoc "org-ref")]]. It works on most libraries, please report ones where it does not work.

** Changes to org-mode behavior
jmax advises C-c C-c behavior so it does not remove LaTeX overlays on equations.

jmax provides `org-toggle-latex-overlays'.

jmax refreshes all images after you execute a src-block.

* Version control in jmax
We use git for version control. There are three styles of using git with jmax:
1. The emacs "vc-" commands and shortcuts
2. The magit library
3. The command line - use it in a terminal

** version control on a single file
I find these keyboard short cuts handy for working on a single file.

| C-x v v | Does the next obvious vc thing, either add file or commit it. |
| C-x v = | Shows a diff of the current file compared to the last commit. |
| C-x v l | Show the current git log                                      |
| C-x v p | Push current commits                                          |
| C-x v P | Pull                                                          |
| C-x v u | Revert last commit                                            |
| C-x v s | Add a tag to the repo (it must be clean)                      |
| C-x v t | Run `magit-status' for everything more complicated.           |

There are many more commands under menu Tools -> Version Control.

magit is pretty awesome. It is worth reading the manual info:magit.

** Track changes
The use of version control allows us to do track changes in jmax! You need to have a wdiff program (e.g. https://www.gnu.org/software/wdiff/) installed. We use a fork https://github.com/jkitchin/criticmarkup-emacs to enable [[http://criticmarkup.com][CriticMarkup]] in Emacs, with some extensions we have written.

- `cm-wdiff-buffer-with-file' :: Show a track change of current version with last saved version

- `cm-wdiff-git' :: Show a track change between two git versions of the open file.

You can turn track changes on with the command `cm-follow-changes'. There is a hydra menu function `cm/body' that provides easy access to turn on track changes, navigate the changes, accept/reject them, etc...

* TODO Scientific writing
See `org-ref'.

** TODO spell checking

* TODO Productivity
** hotspots
The `hotspots' command provides a simple interface to do common things like run the `org-agenda' command, open files you use often, etc...

For example to get easy commands to open my Google calendar, contatcts, agenda, and open my CV I have something like this in my user.el file:

#+BEGIN_SRC emacs-lisp
(setq jmax-user-hotspot-commands
      '(("Calendar" . (lambda ()
			(browse-url "https://www.google.com/calendar/render")))
	("Contacts" . helm-org-contacts)
	("Agenda" . (lambda () (org-agenda "" "w")))
	("CV" . (lambda ()
		  (org-open-file
		   "/Users/jkitchin/Dropbox/CMU/CV and bios/kitchin_cv.docx"
		   '(16))))))
#+END_SRC


** Org contacts
** Email
** RSS/elfeed

* Description of the files in jmax
** [[./init.el]]
Here is where the initialization starts. This is where Emacs checks if jmax is up to date.

The first thing this does is load [[./user/preload.el]]

If you don't want jmax to auto-update all the time put this in that file.

#+BEGIN_SRC emacs-lisp
(setq jmax-auto-update nil)
#+END_SRC

You would also set jmax-user-theme in the preload file if you want something other than leuven.

** [[./packages.el]]
Here is where the packages get installed.

** [[./jmax.el]]

This is the next file to get loaded. This is where most of the Emacs configuration is done. It is mostly loading and configuring packages.

** [[./jmax-utils.el]]
This file contains some convenient utility functions

** [[./python-setup.el]]
This file sets up python mode, and some functions for org-mode and python.

** [[./jmax-org.el]]
This file is where org-mode is configured.

** [[file:email.el]]
This library contains functions for sending emails from Emacs, e.g. to email a selected region, buffer, and other things.

** file:mail-merge.el
Bring mail-merge to org-mode and emacs.

** file:kitchinhub.el
Some convenience functions for using github. Most importantly: elisp:kitchingroup

** file:words.el
Convenient functions to look up things in Emacs.

** file:ore.el
Org-element explorer elisp:ore will tell you about the element at point.

** [[file:ox-manuscript.el]]
This library allows us to export org-mode files to scientific manuscripts.

** file:org-ref
The reference manager for org-mode. Helps with bibliographies, citations, and cross-references.

** file:cm-mods.el
Extensions for `cm-mode' to bring track changes to Emacs and org-mode.

** [[file:ox-archive]]
** [[file:ox-cmu-ms-report.el]]
** [[file:ox-cmu-qualifier.el]]
** [[file:ox-cmu-dissertation.el]]
** user directory
Put your personal setup and overrides here. Everything in this directory will get loaded, in no particular order.

** [[file:themes]]
Leuven is the best looking theme for org-mode in my opinion. It is the default.

There are several alternative themes here including the popular zenburn and solarized themes.

Set one of these like this in your preload.el file:

#+BEGIN_SRC emacs-lisp
(load-theme 'zenburn t)
#+END_SRC

#+RESULTS:
: t

#+BEGIN_SRC emacs-lisp
(setq jmax-user-theme 'zenburn)
#+END_SRC

Some people like the Tomorrow themes (https://emacsthemes.com/themes/sanityinc-tomorrow-themes.html). Try it out.
#+BEGIN_SRC emacs-lisp
(add-to-list
 'custom-theme-load-path
 (expand-file-name "themes/tomorrow-theme/GNU Emacs" starter-kit-dir))

(load-theme 'tomorrow-day)
#+END_SRC

#+RESULTS:
: t

Or the solarized themes
#+BEGIN_SRC emacs-lisp
(add-to-list
 'custom-theme-load-path
 (expand-file-name "themes/emacs-color-theme-solarized" starter-kit-dir))

(load-theme 'solarized-dark)
#+END_SRC

#+RESULTS:
: t

* TODO Latex setup
[[./texmf]] contains a texmf setup you can use with your latex setup. I don't think I actually use this anymore. It looks like I used to use it in Windows though [[file:texmf/README.org][(file:texmf/README.org]])
