#+TITLE: jmax - John's customizations to maximize Emacs

Try it you will like it. These customizations have been compiled and derived from prelude and the emacs24-starterkit.

Clone the git repository, change into the jmax directory, and run this command:
#+begin_src sh
emacs -q -l init.el
#+end_src

This will load the emacs on your path, without using whatever you have defined in .emacs.d.

The first time you run this, a lot of packages will be downloaded into the elpa folder. This takes a few minutes. 

You should clone the org-mode repository, and run the make command to build the autoloads. I usually use =make up2= which updates the git repository. 

#+BEGIN_SRC sh
git clone git://orgmode.org/org-mode.git
cd org-mode
make autoloads
#+END_SRC

That is it.

* Project goal
=jmax= is a customized version of emacs to facilitate authoring and consuming org-mode based technical documents.

All of the emacs customization is performed in an org-mode file.




