#+TITLE: jmax - John's customizations to maximize Emacs

Try it you might like it. These customizations have been compiled and derived from prelude and the emacs24-starterkit, and my own emacs hackery.

* Installation
To install this, clone the git repository, change into the jmax directory, and run this command:
#+begin_src sh
emacs -q -l init.el
#+end_src

This will load the emacs on your path, without using whatever you have defined in .emacs.d.

The first time you run this, a lot of packages will be downloaded into the elpa folder. This takes a few minutes. You might have to restart emacs.

** Windows users
There is an emacs binary in this repository for Windows. This [[./jmax.bat]] file should automatically run emacs with the right libraries.

** Other software you probably need

1. Python https://www.enthought.com/products/canopy/ (Windows, Mac and Linux)
2. LaTeX  https://www.tug.org/texlive/doc.html (Windows, Linux) ([[https://www.tug.org/mactex/][Mac]])
3. git    [[http://git-scm.com/download/win][Windows]] [[http://git-scm.com/download/mac][Mac]] [[http://git-scm.com/download/linux][Linux]]
4. Any other languages that will be used, e.g., Ruby, R, Matlab, compilers, etc...


* Customization
These files contain variables with paths specific to your computer. You probably need to change them.

To set the variables for our org-bibliography functionality you can run:
M-x customize-group jorg-bib

As an alternative, put these variables into a .el file in the user directory. You will want to modify them for your needs of course.

#+BEGIN_SRC emacs-lisp
(setq reftex-default-bibliography '("~/Dropbox/bibliography/references.bib"))

;; see jorg-bib.el for use of these variables
(setq jorg-bib-bibliography-notes "~/Dropbox/bibliography/notes.org"
      jorg-bib-default-bibliography '("~/Dropbox/bibliography/references.bib")
      jorg-bib-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

;;Tell the program who you are and setup for email
(setq user-full-name "John Kitchin"
      andrewid "jkitchin"
      user-mail-address "jkitchin@andrew.cmu.edu"
      ;; specify how email is sent
      send-mail-function 'smtpmail-send-it
      ;; used in message mode
      message-send-mail-function 'smtpmail-send-it
      smtpmail-smtp-server "smtp.andrew.cmu.edu"
      smtpmail-smtp-service 587)
#+END_SRC

* What do these files do?

file:jmax.el does most of the setup that is not related to org-mode. It provides some useful functions. The ones I use the most are get-path, and insert-relative-path.

[[file:jmax-org.el]] is responsible for how we customize org-mode to work for us.

** Scientific manuscript preparation
See [[./examples]] for many examples of preparing scientific manuscripts for submission to ACS, APS, Elsevier and Springer journals.

We have a pretty decent way of handling citations and references provided by [[file:jorg-bib.el]]. This file sets up how bibtex keys are made and provides a lot of new links for org-mode for citations, references, labels, and bibliography files. 

See this example for the basics [[file:examples/technical-documents-in-org.org]].

If you are a student at CMU, you may appreciate:
- Writing your MS report in org-mode [[file:ox-cmu-ms-report.el]]
- Writing your PhD qualifier or proposal in org-mode file:ox-cmu-qualifier.el
- Writing your PhD dissertation in org-mode [[file:ox-cmu-dissertation.el]]

** Create standalone org-archives
Ever wanted to package up an org-file and all the figures, files and directories it references so you can email it to someone? Check out [[file:ox-archive.el]].


** Handy email functions
[[file:email.el]] provides functions to email a region, or an org-heading conveniently.


