#+TITLE: jmax - John's customizations to maximize Emacs

Try it you might like it. These customizations have been compiled and derived from prelude and the emacs24-starterkit, and my own emacs hackery.

* Installation
To install this, clone the git repository, change into the jmax directory, and run this command:
#+begin_src sh
emacs -q -l init.el
#+end_src

This will load the emacs on your path, without using whatever you have defined in .emacs.d.

The first time you run this, a lot of packages will be downloaded into the elpa folder. This takes a few minutes. You might have to restart emacs.

** Windows users
There is an emacs binary in this repository for Windows. This [[./jmax.bat]] file should automatically run emacs with the right libraries.

** Other software you probably need

1. Python https://www.enthought.com/products/canopy/ (Windows, Mac and Linux)
2. LaTeX  https://www.tug.org/texlive/doc.html (Windows, Linux) ([[https://www.tug.org/mactex/][Mac]])
3. git    [[http://git-scm.com/download/win][Windows]] [[http://git-scm.com/download/mac][Mac]] [[http://git-scm.com/download/linux][Linux]]
4. Any other languages that will be used, e.g., Ruby, R, Matlab, compilers, etc...

For some LaTeX packages installed in jmax, you need to add them to your LaTeX path. For TeXlive distributions, do something like this:

#+BEGIN_SRC sh
tlmgr conf texmf TEXMFHOME "~/Dropbox/kitchingroup/jmax/texmf"
#+END_SRC

** Spell checking on windows
Install aspell http://ftp.gnu.org/gnu/aspell/w32/Aspell-0-50-3-3-Setup.exe
and this dictionary  http://ftp.gnu.org/gnu/aspell/w32/Aspell-en-0.50-2-3.exe.

In your init file:

#+BEGIN_SRC emacs-lisp
;; set i(a)spell options on different machines
(setq ispell-personal-dictionary (concat starter-kit-dir "user/.ispell"))

;; adjust this path if it is not where aspell got installed
(setq-default ispell-program-name "C:/Program Files/Aspell/bin/aspell.exe")
#+END_SRC

** Mac users
I installed emacs from homebrew:

#+BEGIN_SRC sh
brew install emacs --with-gnutls --with-imagemagick --with-librsvg --with-x --use-git-head --HEAD --cocoa
#+END_SRC

This got me:
#+BEGIN_EXAMPLE
GNU Emacs 24.4.50.1 (x86_64-apple-darwin13.3.0, NS appkit-1265.21 Version 10.9.4 (Build 13E28)) of 2014-08-07 
#+END_EXAMPLE

I installed git from http://git-scm.com/download/mac

Enthought Canopy has a Mac version.

and MacTeX from http://www.tug.org/mactex.

After that, I was able to clone jmax as described above, and I used the jmax-mac.sh script to open emacs configured to use jmax.

I have previously used  Emacs 24.3 from http://emacsformacosx.com. I do not recall why I switched to brew, but I think the reason was to get gnutls support for email authentication.

* Customization
These files contain variables with paths specific to your computer. You probably need to change them.

To set the variables for our org-bibliography functionality you can run:
M-x customize-group org-ref

As an alternative, put these variables into a .el file in the user directory. You will want to modify them for your needs of course. Here is some of what I have in a file in user/jkitchin.el.

#+BEGIN_SRC emacs-lisp
(setq reftex-default-bibliography '("~/Dropbox/bibliography/references.bib"))

;; see org-ref.el for use of these variables
(setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
      org-ref-default-bibliography '("~/Dropbox/bibliography/references.bib")
      org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

;;Tell the program who you are and setup for email
(setq user-full-name "John Kitchin"
      andrewid "jkitchin"
      user-mail-address "jkitchin@andrew.cmu.edu"
      ;; specify how email is sent
      send-mail-function 'smtpmail-send-it
      ;; used in message mode
      message-send-mail-function 'smtpmail-send-it
      smtpmail-smtp-server "smtp.andrew.cmu.edu"
      smtpmail-smtp-service 587)
#+END_SRC

* What do these files do?

file:jmax.el does most of the setup that is not related to org-mode. It provides some useful functions. The ones I use the most are get-path, and insert-relative-path.

[[file:jmax-org.el]] is responsible for how we customize org-mode to work for us.

** Scientific manuscript preparation
See [[./examples]] for many examples of preparing scientific manuscripts for submission to ACS, APS, Elsevier and Springer journals.

We have a pretty decent way of handling citations and references provided by [[file:org-ref/org-ref.org]]. This file sets up how bibtex keys are made and provides a lot of new links for org-mode for citations, references, labels, and bibliography files. 

See this example for the basics [[file:examples/technical-documents-in-org.org]].

If you are a student at CMU, you may appreciate:
- Writing your MS report in org-mode [[file:ox-cmu-ms-report.el]]
- Writing your PhD qualifier or proposal in org-mode file:ox-cmu-qualifier.el
- Writing your PhD dissertation in org-mode [[file:ox-cmu-dissertation.el]]

** Create standalone org-archives
Ever wanted to package up an org-file and all the figures, files and directories it references so you can email it to someone? Check out [[file:ox-archive.el]].

** Handy email functions
[[file:email.el]] provides functions to email a region, or an org-heading conveniently.


