#+LATEX_CLASS: revtex4-1
#+LATEX_CLASS_OPTIONS: [aps,prb,citeautoscript,preprint,citeautoscript,showkeys]
#+OPTIONS: toc:nil title:nil author:nil
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[version=3]{mhchem}

\title{put your title here}
\author{Some Name}
\altaffiliation[Also at ]{Department of Materials Science and Engineering, Carnegie Mellon University, 5000 Forbes Ave, Pittsburgh, PA 15213}

\author{John R. Kitchin}
\email{jkitchin@andrew.cmu.edu}
\affiliation{National Energy Technology Laboratory-Regional University Alliance (NETL-RUA), Pittsburgh, Pennsylvania 15236}
\altaffiliation[Also at ]{Department of Chemical Engineering, Carnegie Mellon University, 5000 Forbes, Ave, Pittsburgh, PA 15213}

\date{\today}

#+begin_abstract
put your abstract here
#+end_abstract

\pacs{}
\keywords{kw1, kw2}
\maketitle

* Introduction

Introduce your topic here, with some references  cite:Fossdal2004,Alexandrov2011 photovoltaics, cite:Man2011,Qi2011 spintronics and other forms of magnetic coupling, cite:Walsh2008,Lee2010,Hong2012 exhaust gas CO cite:Xiang2013,Patel2013 and NO$_{x}$ cite:Civera2003,Gallucci2012,Kim2010 treatment, and steam reformation. cite:Martinelli2012 
Here is an equation

\begin{equation}
nABO_{3} \rightarrow nABO_{3-\frac{1}{n}} + \frac{1}{2} O_{2} (g) \label{eq-redox}
\end{equation}


* Methods
** first subsection

Unless otherwise stated, DFT calculations were performed using the Vienna Ab-initio Simulation Package (VASP 5.2.12) cite:Kresse1996,Kresse1999. The Perdew-Burke-Ernzerhof (PBE) parameterization of the Generalized Gradient Approximation (GGA) cite:Perdew1996 was used to account for electron exchange and correlation. Pseudopotentials generated by the Projected Augmented Wave (PAW) cite:Blochl1994 method were used. The default PAW pseudopotentials provided by VASP were used for all atoms. Typical computational parameters characteristic of a plotted set of calculations completed in this study are a 550 eV plane-wave energy cutoff, a $6 \times 6 \times 6$ Monkhorst-Pack cite:Monkhorst1976 $k$-point sampling mesh set with respect to the perovskite unit cell (containing 5, 10, or 20 atoms in this study), and a 0.02 eV/\AA force tolerance on each atom for structural relaxation calculations.



** a suanother subsection
discuss some other methods.


* Results and Discussion

General results and discussion

** subsection 1

with the specific results


* Summary and Conclusions

Put your summary and conclusions here



\begin{acknowledgments}
As part of the National Energy Technology Laboratory's Regional University Alliance (NETL-RUA), a collaborative initiative of the NETL, this technical effort was performed under the RES contract DE-FE0004000. The authors of this paper also thank Dr. Heather Kulik for her contributions to discussions involving the use of the Hubbard $U$ method in this article.
\end{acknowledgments}


bibliography:references.bib





* build							   :noexport:
[[elisp:(kg-vanilla-export-and-build t)]]

* notes about revtex4-1						   :noexport:
No default packages are provided for this, so you must use headings like this:
#+BEGIN_EXAMPLE
#+LATEX_CLASS: revtex4-1
#+LATEX_CLASS_OPTIONS: [aps,prb,citeautoscript,preprint,citeautoscript,showkeys]
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[version=3]{mhchem}
#+END_EXAMPLE

To setup what you need for the manuscript.

Type C-c C-e j o 

or run this: elisp:(ox-manuscript-export-and-build-and-open)
